name: my_complex
description: naive implementation of cartesian and polar complex numbers.
version: 0.0.5
author: Edouard Tavinor <email@example.com>
homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

#dependencies:
#  lib_name: any

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
